# Generated by Django 4.2.9 on 2024-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
