# Generated by Django 4.2.9 on 2024-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_actors_review_content_review_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='actors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/200/300'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='running_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
