# Generated by Django 4.2.9 on 2024-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_actors_alter_review_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(),
        ),
    ]
