# Generated by Django 4.2.9 on 2024-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
    ]
