# Generated by Django 4.2.9 on 2024-01-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_ideastar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100, verbose_name='아이디어명'),
        ),
    ]
