# Generated by Django 4.2.9 on 2024-01-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtool', '0001_initial'),
        ('ideas', '0004_alter_idea_content_alter_idea_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtool.devtool', verbose_name='개발 도구'),
        ),
    ]
